### PR TITLE
Use eval for set_color on operator so that we can use flags

### PR DESCRIPTION
**Pull request by amir20**
Any objection to using `eval` for `set_color`? This allows to do 

`set -U fish_color_operator '-o cc3' ` so that the operator can be bold.

### CODE REVIEW

**Comment by bucaran** [comment]
Those vars are arrays, so `set_color` should work with `-o cc3` just fine AFIK

**Comment by amir20** [comment]
I did `set -U fish_color_operator '-o cc3'` without eval and it didn't work. It just turned white.

**Comment by bucaran** [comment]
Yes, you need to set it to `set -U fish_color_operator -o cc3`, without the quotes.

**Comment by amir20** [comment]
Oh hmm. Let me try.

**Comment by amir20** [comment]
Woohoooo it works! Closing. Good to know 👍

**Pull request closed without merging**
